-- ============================================================================
-- migration 049: CS CSAT (Customer Satisfaction) -- Sprint 50d
--
-- Why this exists
--   The SLA dashboard now shows speed (FRT) and durability (TTR) per
--   agent, but neither captures whether the customer actually FELT
--   helped. CSAT is the classic "after a resolution, ask the customer
--   to rate the interaction 1-5" pattern. We add it as a stand-alone
--   record so we can:
--     * compute avg rating + thumbs-up % on the dashboard
--     * cross-join with cs_contact_link to attribute by customer
--     * cross-join with the assigneeId on Chatwoot to attribute by agent
--
-- Token-based public submit
--   The submit endpoint is anonymous (no JWT) because the customer
--   will follow a one-time link from email / SMS / WhatsApp. A 24-char
--   opaque token is generated at link-creation time and validated on
--   submit. Tokens are single-use; once a response is recorded the
--   row's `submitted_at` is non-null and further submits 409 out.
--
-- Time-to-survive (TTL)
--   Tokens expire after 30 days (`expires_at`). Beyond that, the link
--   returns 410 Gone. This prevents stale links from being mined.
--
-- What this migration does
--   1. Creates cs_csat_response with the rating + comment + token state
--   2. Adds indexes for the two main read paths (by conv + by date)
--
-- Why no foreign keys
--   Same reason as cs_contact_link in migration 043: Chatwoot's
--   conversation ids live in a separate database. We carry the id as
--   a plain bigint and let the application layer reconcile.
-- ============================================================================

CREATE TABLE IF NOT EXISTS cs_csat_response (
    id                    BIGINT       NOT NULL AUTO_INCREMENT,
    -- One-time opaque token used in the public survey URL.
    -- Generated by the backend as 24 base32 chars (URL-safe).
    token                 VARCHAR(64)  NOT NULL,
    -- Chatwoot conversation id this rating is anchored to.
    chatwoot_conversation_id BIGINT    NOT NULL,
    -- Chatwoot contact id (the customer). NULL only if Chatwoot didn't
    -- have one at link-generation time (extreme edge case).
    chatwoot_contact_id   BIGINT       NULL,
    -- AgriOS Customer id, via cs_contact_link. NULL for inbound
    -- WebWidget conversations from contacts that never matched a
    -- customer row.
    agrios_customer_id    BIGINT       NULL,
    -- The agent who held the conversation when the link was created.
    -- Stored at link-gen time, not at submit time, so post-submission
    -- reassignment doesn't change attribution.
    chatwoot_agent_id     BIGINT       NULL,
    -- 1..5 -- NULL until the customer actually submits.
    rating                TINYINT      NULL,
    -- Optional free-form comment, capped server-side at 2000 chars.
    comment               VARCHAR(2000) NULL,
    -- Filled when the customer submits. NULL = link issued but not
    -- yet acted on.
    submitted_at          DATETIME     NULL,
    -- TTL gate. 30 days from creation by default.
    expires_at            DATETIME     NOT NULL,
    -- Audit columns.
    created_by            BIGINT       NULL,
    created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
                                     ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_cs_csat_token (token),
    KEY idx_cs_csat_conv (chatwoot_conversation_id),
    KEY idx_cs_csat_submitted_at (submitted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Permission seed: agent must hold cs:csat:send to generate a link.
-- All built-in MANAGER / LEADER / PACKHOUSE / SALES roles get it.
-- WORKER does not (they only do warehouse / production work).
INSERT IGNORE INTO sys_menu
    (id, parent_id, code,             name,                 type,    path, perms,            sort, visible)
VALUES
    (997, 0,        'cs.csat.send',   'Send CSAT survey',   'button', NULL, 'cs:csat:send',   90,   0);

INSERT IGNORE INTO sys_role_menu (role_id, menu_id)
SELECT r.id, 997 FROM sys_role r
WHERE r.code IN ('SUPER_ADMIN', 'MANAGER', 'LEADER', 'PACKHOUSE', 'SALES');
