package ai.toafrica.agrios.qc.service;

import ai.toafrica.agrios.qc.vo.GapReportData;
import ai.toafrica.agrios.qc.vo.TraceVO;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * GAP / HACCP audit report — Excel (.xlsx) renderer (Sprint 28).
 *
 * Multi-sheet workbook designed for auditors who need to filter/sort:
 *   Sheet 1: Summary       — header, verdict, batch info, plot info, harvest
 *   Sheet 2: Activities    — chronological field log
 *   Sheet 3: PHI Checks    — per-spray compliance verdict
 *   Sheet 4: Inputs Source — inbound + originating PO
 *   Sheet 5: QC            — inspection records
 *   Sheet 6: Packing       — packings derived from this batch
 *   Sheet 7: Shipments     — sales orders containing this batch
 *   Sheet 8: Events        — complaints + recalls
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class GapReportXlsxService {

    private final GapReportService gapReportService;
    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd");
    private static final DateTimeFormatter DATETIME_FMT = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm");

    public byte[] render(String batchCode) {
        GapReportData d = gapReportService.buildBatchReport(batchCode);
        try (XSSFWorkbook wb = new XSSFWorkbook(); ByteArrayOutputStream os = new ByteArrayOutputStream()) {
            Styles s = new Styles(wb);
            writeSummary(wb, s, d);
            writeActivities(wb, s, d);
            writePhi(wb, s, d);
            writeInbound(wb, s, d);
            writeQc(wb, s, d);
            writePacking(wb, s, d);
            writeShipments(wb, s, d);
            writeEvents(wb, s, d);
            wb.write(os);
            byte[] bytes = os.toByteArray();
            log.info("[GapReportXlsx] batch={} xlsx={}KB verdict={}",
                    batchCode, bytes.length / 1024, d.getVerdict());
            return bytes;
        } catch (Exception e) {
            throw new RuntimeException("Failed to render GAP report XLSX", e);
        }
    }

    // ----------------------------------------------------------------
    // Sheet builders
    // ----------------------------------------------------------------
    private void writeSummary(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Summary");
        TraceVO t = d.getTrace();
        int r = 0;
        title(sh, r++, "GAP / HACCP AUDIT REPORT", s.titleStyle);
        sh.addMergedRegion(new CellRangeAddress(0, 0, 0, 3));
        kv(sh, r++, "Batch Code", t.getBatch().getCode(), s);
        kv(sh, r++, "Verdict", d.getVerdict(), s, verdictStyle(s, d.getVerdict()));
        kv(sh, r++, "Crop / Variety",
                t.getBatch().getCropName() + (t.getBatch().getVarietyName() == null ? "" : " / " + t.getBatch().getVarietyName()), s);
        kv(sh, r++, "Qty (kg)", qty(t.getBatch().getQtyKg()), s);
        kv(sh, r++, "Created Date", fmtDate(t.getBatch().getCreatedDate()), s);
        kv(sh, r++, "Generated At", fmtDateTime(d.getGeneratedAt()), s);
        kv(sh, r++, "Generated By", safe(d.getGeneratedByName()), s);
        r++; // spacer
        if (t.getPlot() != null) {
            sectionHeader(sh, r++, "Plot", s);
            kv(sh, r++, "Code", t.getPlot().getCode(), s);
            kv(sh, r++, "Name", t.getPlot().getName(), s);
            kv(sh, r++, "Region", safe(t.getPlot().getRegionName()), s);
            kv(sh, r++, "Area (ha)", qty(t.getPlot().getAreaHa()), s);
            r++;
        }
        if (t.getPlan() != null) {
            sectionHeader(sh, r++, "Planting Plan", s);
            kv(sh, r++, "Code", t.getPlan().getCode(), s);
            kv(sh, r++, "Sow Date", fmtDate(t.getPlan().getPlannedSowDate()), s);
            kv(sh, r++, "Planned Harvest", fmtDate(t.getPlan().getPlannedHarvestDate()), s);
            kv(sh, r++, "Status", safe(t.getPlan().getStatus()), s);
            r++;
        }
        if (t.getHarvest() != null) {
            sectionHeader(sh, r++, "Harvest", s);
            kv(sh, r++, "Code", t.getHarvest().getCode(), s);
            kv(sh, r++, "Date", fmtDate(t.getHarvest().getHarvestDate()), s);
            kv(sh, r++, "Qty (kg)", qty(t.getHarvest().getQtyKg()), s);
            kv(sh, r++, "Operator", safe(t.getHarvest().getOperatorName()), s);
            kv(sh, r++, "GPS", safe(t.getHarvest().getLocationGps()), s);
        }
        sh.setColumnWidth(0, 22 * 256);
        sh.setColumnWidth(1, 48 * 256);
    }

    private void writeActivities(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Activities");
        header(sh, s, "Date", "Type", "Operator", "Input Code", "Input Name", "Active Ingredient", "PHI (d)", "Qty", "Unit");
        if (d.getTrace().getActivities() != null) {
            int r = 1;
            for (TraceVO.ActivityNode a : d.getTrace().getActivities()) {
                if (a.getInputs() == null || a.getInputs().isEmpty()) {
                    Row row = sh.createRow(r++);
                    setCell(row, 0, fmtDate(a.getOccurDate()), s.dataStyle);
                    setCell(row, 1, safe(a.getActivityType()), s.dataStyle);
                    setCell(row, 2, safe(a.getOperatorName()), s.dataStyle);
                    setCell(row, 3, "—", s.dimStyle);
                } else {
                    for (TraceVO.InputUsed iu : a.getInputs()) {
                        Row row = sh.createRow(r++);
                        setCell(row, 0, fmtDate(a.getOccurDate()), s.dataStyle);
                        setCell(row, 1, safe(a.getActivityType()), s.dataStyle);
                        setCell(row, 2, safe(a.getOperatorName()), s.dataStyle);
                        setCell(row, 3, safe(iu.getInputItemCode()), s.dataStyle);
                        setCell(row, 4, safe(iu.getInputItemName()), s.dataStyle);
                        setCell(row, 5, safe(iu.getActiveIngredient()), s.dataStyle);
                        setCell(row, 6, iu.getPhiDays() == null ? "" : iu.getPhiDays().toString(), s.dataStyle);
                        setCell(row, 7, qty(iu.getQty()), s.dataStyle);
                        setCell(row, 8, safe(iu.getUnit()), s.dataStyle);
                    }
                }
            }
        }
        autoSize(sh, 9);
    }

    private void writePhi(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("PHI Checks");
        header(sh, s, "Spray Date", "Input Code", "Input Name", "Active Ingredient", "PHI Days", "Safe From", "Harvest Date", "Verdict");
        if (d.getPhiCompliance() != null && d.getPhiCompliance().getSprayChecks() != null) {
            int r = 1;
            for (GapReportData.SprayCheck c : d.getPhiCompliance().getSprayChecks()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, fmtDate(c.getSprayDate()), s.dataStyle);
                setCell(row, 1, safe(c.getInputCode()), s.dataStyle);
                setCell(row, 2, safe(c.getInputName()), s.dataStyle);
                setCell(row, 3, safe(c.getActiveIngredient()), s.dataStyle);
                setCell(row, 4, c.getPhiDays() == null ? "" : c.getPhiDays().toString(), s.dataStyle);
                setCell(row, 5, fmtDate(c.getSafeDate()), s.dataStyle);
                setCell(row, 6, fmtDate(c.getHarvestDate()), s.dataStyle);
                setCell(row, 7, c.isCompliant() ? "OK" : "BREACH", c.isCompliant() ? s.okStyle : s.failStyle);
            }
        }
        autoSize(sh, 8);
    }

    private void writeInbound(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Inputs Source");
        header(sh, s, "Inbound Code", "Confirmed", "Source PO", "Input Code", "Input Name", "Qty");
        if (d.getTrace().getInbounds() != null) {
            int r = 1;
            for (TraceVO.InboundNode ib : d.getTrace().getInbounds()) {
                if (ib.getItems() == null || ib.getItems().isEmpty()) {
                    Row row = sh.createRow(r++);
                    setCell(row, 0, safe(ib.getCode()), s.dataStyle);
                    setCell(row, 1, fmtDate(ib.getConfirmedAt()), s.dataStyle);
                    setCell(row, 2, safe(ib.getSourceCode()), s.dataStyle);
                } else {
                    for (TraceVO.InputReceived ir : ib.getItems()) {
                        Row row = sh.createRow(r++);
                        setCell(row, 0, safe(ib.getCode()), s.dataStyle);
                        setCell(row, 1, fmtDate(ib.getConfirmedAt()), s.dataStyle);
                        setCell(row, 2, safe(ib.getSourceCode()), s.dataStyle);
                        setCell(row, 3, safe(ir.getInputItemCode()), s.dataStyle);
                        setCell(row, 4, safe(ir.getInputItemName()), s.dataStyle);
                        setCell(row, 5, qty(ir.getQty()), s.dataStyle);
                    }
                }
            }
        }
        autoSize(sh, 6);
    }

    private void writeQc(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("QC");
        header(sh, s, "Code", "Type", "Date", "Inspector", "Result", "Remark");
        if (d.getQcSummary() != null && d.getQcSummary().getInspections() != null) {
            int r = 1;
            for (GapReportData.InspectionEntry e : d.getQcSummary().getInspections()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, safe(e.getCode()), s.dataStyle);
                setCell(row, 1, safe(e.getInspectionType()), s.dataStyle);
                setCell(row, 2, fmtDate(e.getInspectDate()), s.dataStyle);
                setCell(row, 3, safe(e.getInspectorName()), s.dataStyle);
                String result = safe(e.getResult());
                CellStyle st = "pass".equals(result) ? s.okStyle
                        : "fail".equals(result) ? s.failStyle
                        : "conditional_pass".equals(result) ? s.warnStyle : s.dataStyle;
                setCell(row, 4, result, st);
                setCell(row, 5, safe(e.getResultRemark()), s.dataStyle);
            }
        }
        autoSize(sh, 6);
    }

    private void writePacking(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Packing");
        header(sh, s, "Code", "Date", "SKU Code", "SKU Name", "Qty", "Unit");
        if (d.getTrace().getPackings() != null) {
            int r = 1;
            for (TraceVO.PackingNode p : d.getTrace().getPackings()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, safe(p.getCode()), s.dataStyle);
                setCell(row, 1, fmtDate(p.getPackDate()), s.dataStyle);
                setCell(row, 2, safe(p.getSkuCode()), s.dataStyle);
                setCell(row, 3, safe(p.getSkuName()), s.dataStyle);
                setCell(row, 4, qty(p.getQty()), s.dataStyle);
                setCell(row, 5, safe(p.getUnit()), s.dataStyle);
            }
        }
        autoSize(sh, 6);
    }

    private void writeShipments(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Shipments");
        header(sh, s, "Order Code", "Date", "Customer", "Status");
        if (d.getTrace().getOrders() != null) {
            int r = 1;
            for (TraceVO.OrderNode o : d.getTrace().getOrders()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, safe(o.getCode()), s.dataStyle);
                setCell(row, 1, fmtDate(o.getOrderDate()), s.dataStyle);
                setCell(row, 2, safe(o.getCustomerName()), s.dataStyle);
                setCell(row, 3, safe(o.getStatus()), s.dataStyle);
            }
        }
        autoSize(sh, 4);
    }

    private void writeEvents(Workbook wb, Styles s, GapReportData d) {
        Sheet sh = wb.createSheet("Events");
        int r = 0;
        // Complaints
        sectionHeader(sh, r++, "Complaints", s);
        if (d.getComplaints() == null || d.getComplaints().isEmpty()) {
            setCell(sh.createRow(r++), 0, "No complaints.", s.dimStyle);
        } else {
            Row h = sh.createRow(r++);
            String[] cols = {"Code", "Reported", "Category", "Severity", "Status", "Description"};
            for (int i = 0; i < cols.length; i++) setCell(h, i, cols[i], s.headerStyle);
            for (GapReportData.ComplaintEntry c : d.getComplaints()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, safe(c.getCode()), s.dataStyle);
                setCell(row, 1, fmtDateTime(c.getReportedAt()), s.dataStyle);
                setCell(row, 2, safe(c.getCategory()), s.dataStyle);
                setCell(row, 3, safe(c.getSeverity()), s.dataStyle);
                setCell(row, 4, safe(c.getStatus()), s.dataStyle);
                setCell(row, 5, safe(c.getDescription()), s.dataStyle);
            }
        }
        r++;
        // Recalls
        sectionHeader(sh, r++, "Recalls", s);
        if (d.getRecalls() == null || d.getRecalls().isEmpty()) {
            setCell(sh.createRow(r++), 0, "No recalls.", s.dimStyle);
        } else {
            Row h = sh.createRow(r++);
            String[] cols = {"Code", "Triggered", "Status", "Affected Orders", "Reason"};
            for (int i = 0; i < cols.length; i++) setCell(h, i, cols[i], s.headerStyle);
            for (GapReportData.RecallEntry rc : d.getRecalls()) {
                Row row = sh.createRow(r++);
                setCell(row, 0, safe(rc.getCode()), s.dataStyle);
                setCell(row, 1, fmtDateTime(rc.getTriggeredAt()), s.dataStyle);
                setCell(row, 2, safe(rc.getStatus()), s.dataStyle);
                setCell(row, 3, rc.getAffectedOrderCount() == null ? "0" : rc.getAffectedOrderCount().toString(), s.dataStyle);
                setCell(row, 4, safe(rc.getReason()), s.dataStyle);
            }
        }
        autoSize(sh, 6);
    }

    // ----------------------------------------------------------------
    // Cell helpers
    // ----------------------------------------------------------------
    private void title(Sheet sh, int row, String text, CellStyle style) {
        Row r = sh.createRow(row);
        setCell(r, 0, text, style);
    }

    private void sectionHeader(Sheet sh, int row, String text, Styles s) {
        Row r = sh.createRow(row);
        setCell(r, 0, text, s.sectionStyle);
    }

    private void kv(Sheet sh, int row, String k, String v, Styles s) {
        kv(sh, row, k, v, s, s.dataStyle);
    }

    private void kv(Sheet sh, int row, String k, String v, Styles s, CellStyle valueStyle) {
        Row r = sh.createRow(row);
        setCell(r, 0, k, s.keyStyle);
        setCell(r, 1, v, valueStyle);
    }

    private void header(Sheet sh, Styles s, String... cols) {
        Row r = sh.createRow(0);
        for (int i = 0; i < cols.length; i++) setCell(r, i, cols[i], s.headerStyle);
    }

    private void setCell(Row row, int col, String value, CellStyle style) {
        Cell c = row.createCell(col);
        c.setCellValue(value == null ? "" : value);
        if (style != null) c.setCellStyle(style);
    }

    private void autoSize(Sheet sh, int columns) {
        for (int i = 0; i < columns; i++) sh.setColumnWidth(i, 22 * 256);
    }

    private CellStyle verdictStyle(Styles s, String verdict) {
        return switch (verdict == null ? "" : verdict) {
            case "COMPLIANT" -> s.okStyle;
            case "FLAGGED" -> s.warnStyle;
            case "NON_COMPLIANT" -> s.failStyle;
            default -> s.dataStyle;
        };
    }

    private static String fmtDate(LocalDate d) { return d == null ? "" : d.format(DATE_FMT); }
    private static String fmtDateTime(LocalDateTime t) { return t == null ? "" : t.format(DATETIME_FMT); }
    private static String qty(BigDecimal v) { return v == null ? "0" : v.stripTrailingZeros().toPlainString(); }
    private static String safe(String s) { return s == null ? "" : s; }

    // ----------------------------------------------------------------
    // Style bundle — reused across sheets
    // ----------------------------------------------------------------
    static class Styles {
        final CellStyle titleStyle;
        final CellStyle sectionStyle;
        final CellStyle headerStyle;
        final CellStyle keyStyle;
        final CellStyle dataStyle;
        final CellStyle dimStyle;
        final CellStyle okStyle;
        final CellStyle warnStyle;
        final CellStyle failStyle;

        Styles(Workbook wb) {
            DataFormat df = wb.createDataFormat();
            Font titleFont = wb.createFont();
            titleFont.setBold(true);
            titleFont.setFontHeightInPoints((short) 14);

            Font hFont = wb.createFont();
            hFont.setBold(true);
            hFont.setColor(IndexedColors.WHITE.getIndex());

            Font sectionFont = wb.createFont();
            sectionFont.setBold(true);
            sectionFont.setColor(IndexedColors.DARK_GREEN.getIndex());
            sectionFont.setFontHeightInPoints((short) 12);

            Font keyFont = wb.createFont();
            keyFont.setColor(IndexedColors.GREY_50_PERCENT.getIndex());

            titleStyle = wb.createCellStyle();
            titleStyle.setFont(titleFont);

            sectionStyle = wb.createCellStyle();
            sectionStyle.setFont(sectionFont);
            sectionStyle.setBorderBottom(BorderStyle.MEDIUM);

            headerStyle = wb.createCellStyle();
            headerStyle.setFont(hFont);
            headerStyle.setFillForegroundColor(IndexedColors.DARK_GREEN.getIndex());
            headerStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            headerStyle.setBorderBottom(BorderStyle.THIN);

            keyStyle = wb.createCellStyle();
            keyStyle.setFont(keyFont);
            keyStyle.setFillForegroundColor(IndexedColors.GREY_25_PERCENT.getIndex());
            keyStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            dataStyle = wb.createCellStyle();
            dataStyle.setBorderBottom(BorderStyle.THIN);
            dataStyle.setBorderTop(BorderStyle.THIN);
            dataStyle.setBorderLeft(BorderStyle.THIN);
            dataStyle.setBorderRight(BorderStyle.THIN);

            dimStyle = wb.createCellStyle();
            dimStyle.setFont(keyFont);

            okStyle = wb.createCellStyle();
            okStyle.cloneStyleFrom(dataStyle);
            okStyle.setFillForegroundColor(IndexedColors.LIGHT_GREEN.getIndex());
            okStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            warnStyle = wb.createCellStyle();
            warnStyle.cloneStyleFrom(dataStyle);
            warnStyle.setFillForegroundColor(IndexedColors.LIGHT_YELLOW.getIndex());
            warnStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            failStyle = wb.createCellStyle();
            failStyle.cloneStyleFrom(dataStyle);
            failStyle.setFillForegroundColor(IndexedColors.ROSE.getIndex());
            failStyle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        }
    }
}
